### ISSUE TITLE
Separate projects

### ISSUE THREAD

**Issue by zethon** [zethon/Owl#42]
There will three repositories

* OwlLibrary - contains common functionality such as Lua/C++ parser implementation and common types
  * Will require external libraries in order to use
  * Unit Tests will be optionally built and run (and require the linkage)

* OwlConsole - OwlConsole app, will use OwlLibrary

* Owl - Owl GUI app, will use OwlLibrary

**Comment by aclaure** [comment]
Nah, bad idea.
